FROM python:3.12-slim

WORKDIR /app

# Copiamos el requirements desde la subcarpeta
COPY ventas_api/requirements.txt .

# Instalamos sin caché para que la imagen pese menos
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos el contenido de ventas_api al directorio 
COPY ventas_api/ .

EXPOSE 5000

CMD ["python", "app.py"]